[project]
name = "simple-task-manager-practice"
version = "0.1.0"
description = "A simple task manager for release practice"
authors = [{ name="Amy", email="yam532004@gmail.com" }]
readme = "README.md"
requires-python = ">=3.9"
